[env:esp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit DRV2605 Library@^1.2.4
build_flags =
    -D FW_VERSION=\"0.1.0\"
    ; -D USE_LRA            ; uncomment if the motors are LRAs instead of ERMs
